name: vscout_cli
description: Scouting software for robotics competitions.
authors: [Sean D'Souza <seangdsouza@gmail.com>, Jeffrey Li <dr.cheddar@outlook.com>]
homepage: https://vscout.readthedocs.io/

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: any
  provider: ^3.0.0
  dynamic_theme: ^1.0.0
  flutter_svg: ^0.14.0


dev_dependencies:
  pedantic: ^1.7.0
  sembast: ^2.0.1+2
  path: ^1.6.2
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0
  built_value: ^6.7.0
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  uuid: ^2.0.2
  safe_config: ^2.0.2
  yaml: ^2.1.16 
  tuple: ^1.0.2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

executables:
  vscout.dart:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: icomoon
    fonts:
      - asset: fonts/icomoon.ttf
  - family: VscoutLogo
    fonts:
      - asset: fonts/VscoutLogo.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
